name: lint-build-push-deploy
on:
  push:
    tags:
      - "*"
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          verbose: true

      - name: test
        run: ./ci/test.sh

  build-push:
    needs: [lint-test]
    uses: lehigh-university-libraries/gha/.github/workflows/build-push-ghcr.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit

  deploy:
    needs: [build-push]
    uses: lehigh-university-libraries/gha/.github/workflows/linderman-deploy.yaml@main
    with:
      url: https://apps-test.lib.lehigh.edu/_rollout
    secrets: inherit
    permissions:
      contents: read
      id-token: write
