name: validate renovate.json5

on:
  pull_request:
    paths:
      - "renovate.json5"
env:
  LOG_LEVEL: debug

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 22

      - run: npx -p renovate renovate-config-validator renovate.json5
